import Head from 'next/head';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { useState, useEffect, useRef } from 'react';
import Link from 'next/link';

export default function ApproachPage() {
  const [dealVolume, setDealVolume] = useState(0);
  const [countries, setCountries] = useState(0);
  const [experience, setExperience] = useState(0);
  const factsRef = useRef(null);
  const [factsVisible, setFactsVisible] = useState(false);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) setFactsVisible(true);
      },
      { threshold: 0.1 }
    );
    if (factsRef.current) observer.observe(factsRef.current);
    return () => {
      if (factsRef.current) observer.unobserve(factsRef.current);
    };
  }, []);

  useEffect(() => {
    if (factsVisible) {
      let vInterval = setInterval(() => {
        setExperience(prev => (prev >= 20 ? 20 : prev + 1));
      }, 100);
      let cInterval = setInterval(() => {
        setDealVolume(prev => (prev >= 1300 ? 1300 : prev + 50));
      }, 30);
      let eInterval = setInterval(() => {
        setCountries(prev => (prev >= 8 ? 8 : prev + 1));
      }, 200);
      return () => {
        clearInterval(vInterval);
        clearInterval(cInterval);
        clearInterval(eInterval);
      };
    }
  }, [factsVisible]);

  const valueCards = [
    {
      title: "Nimble Execution",
      description: "Nextgeninvest believes that it excels in rapid execution and agile capital deployment, distinguishing itself through speed and flexibility. This approach gives Nextgeninvest the potential to secure attractive yet competitive transaction terms and to ensure a continuous flow of competitive deals.",
      icon: "bi-lightning-charge"
    },
    {
      title: "Asset Expertise",
      description: "Our team’s asset knowledge combined with the significant asset data generated by our historical investing activity enables us to seek to structure reasonable downside protection and quickly respond to market changes.",
      icon: "bi-gem"
    },
    {
      title: "Long-standing Relationships",
      description: "Nextgeninvest prides itself on developing long-term relationships with counterparties, believing this provides us with a strong origination and investment management network that helps facilitate our approach.",
      icon: "bi-hand-thumbs-up"
    }
  ];

  return (
    <>
      <Head>
        <title>Our Approach | Nextgeninvest | Global Investment Firm</title>
      </Head>

      <Navbar />

      <main>
        {/* Page Hero - Matching About UI */}
        <section className="position-relative py-5 overflow-hidden hero-section-standard" style={{ minHeight: '60vh', display: 'flex', alignItems: 'center', backgroundColor: '#1F4D3A' }}>
          <div className="position-absolute w-100 h-100 opacity-25" style={{ top: 0, left: 0, backgroundImage: 'url("https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80&w=2000")', backgroundSize: 'cover', backgroundPosition: 'center' }}></div>
          <div className="container mt-5 pt-5 position-relative" style={{ zIndex: 1 }}>
            <div className="row">
              <div className="col-lg-8 fade-up active">
                <h6 className="text-gold mb-3 fw-bold" style={{ letterSpacing: '4px' }}>INVESTMENT PHILOSOPHY</h6>
                <h1 className="display-3 text-white mb-4 fw-bold">A Disciplined Path to <span className="text-gold">Value Creation</span></h1>
                <p className="lead text-white-50 fs-4">We combine rigorous fundamental analysis with a flexible investment approach to navigate complexity and deliver superior risk-adjusted returns.</p>
              </div>
            </div>
          </div>
        </section>

        {/* 2. Differentiated exposure prioritizing cash flow and downside protection */}
        <section className="bg-white py-5">
          <div className="container">
            <div className="row align-items-center g-5">
              <div className="col-lg-6 fade-up">
                <h2 className="section-title">Differentiated exposure prioritizing cash flow and downside protection</h2>
                <p className="mb-4">Nextgeninvest’s investment approach aims to provide investors with asset-rich and cash-flowing exposure according to their risk-return and asset appetite, with a consistent focus on seeking to provide reasonable downside protection. We do this by acting as a capital solutions or liquidity provider to asset owners and originators, often in the form of bilaterally-sourced, asset-based loans or financing facilities. Most of our investments are typically structured with self-amortization or cash flow to de-risk over time and generate yield. Through granular structuring and asset selection, we aim to deliver attractive risk-adjusted performance throughout various economic cycles or market conditions.</p>
              </div>
              <div className="col-lg-6 fade-up">
                <div className="position-relative p-0 p-md-4">
                  <img src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800" className="img-fluid shadow-lg" alt="Analysis" />
                  <div className="position-absolute top-0 end-0 p-4 bg-primary-green text-white d-none d-md-block" style={{ transform: 'translate(20%, -20%)' }}>
                    <h4 className="mb-0 text-gold">20+ Years</h4>
                    <small>of Market Insight</small>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* 3. Facts Section - Minimalist Architectural Metrics */}
        <section ref={factsRef} className="py-section-minimalist position-relative overflow-hidden" style={{ backgroundColor: '#1F4D3A' }}>
          <div className="container position-relative" style={{ zIndex: 10 }}>
            <div className="row g-0">
              <div className="col-lg-4 border-end-gold fade-up">
                <div className="minimal-fact-box p-4 p-md-5 text-center">
                  <div className="minimal-value-wrap">
                    <h2 className="min-number">{experience}</h2>
                  </div>
                  <div className="min-divider"></div>
                  <h4 className="min-label">Years of Experience</h4>
                </div>
              </div>
              <div className="col-lg-4 border-end-gold fade-up">
                <div className="minimal-fact-box p-4 p-md-5 text-center">
                  <div className="minimal-value-wrap">
                    <h2 className="min-number">{dealVolume}</h2>
                    <span className="min-suffix">+</span>
                  </div>
                  <div className="min-divider"></div>
                  <h4 className="min-label">Transactions</h4>
                </div>
              </div>
              <div className="col-lg-4 fade-up">
                <div className="minimal-fact-box p-4 p-md-5 text-center">
                  <div className="minimal-value-wrap">
                    <h2 className="min-number">{countries}</h2>
                  </div>
                  <div className="min-divider"></div>
                  <h4 className="min-label">global Offices</h4>
                </div>
              </div>
            </div>
          </div>
          <div className="arch-overlay"></div>
        </section>

        {/* 4. Tailored investment solutions */}
        <section className="bg-light py-5">
          <div className="container">
            <div className="row align-items-center flex-column flex-lg-row-reverse g-5">
              <div className="col-lg-6 fade-up">
                <h2 className="section-title">Tailored investment solutions</h2>
                <p className="mb-4">Nextgeninvest manages assets on behalf of a diverse base of global institutional investors and strives to provide tailored solutions that seek to address their needs. With the capability to rotate across the risk spectrum as market conditions evolve, we believe our investors benefit from the strong origination pipeline and relationships that result from our comprehensive capital strategy and investment flexibility. We will make Form 20 available to our investors upon request.</p>
                <Link href="/contact" className="btn btn-premium px-5 py-3">Contact Us</Link>
              </div>
              <div className="col-lg-6 fade-up">
                <img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&q=80&w=800" className="img-fluid rounded shadow mt-4 mt-lg-0" alt="Tailored Solutions" />
              </div>
            </div>
          </div>
        </section>

        {/* 5. Creative capital for asset-rich opportunities */}
        <section className="bg-white overflow-hidden py-5">
          <div className="container">
            <div className="row align-items-center g-5">
              <div className="col-lg-5 order-2 order-lg-1 fade-up">
                <div className="asset-text-content">
                  <h6 className="text-gold small mb-3 fw-bold" style={{ letterSpacing: '5px' }}>CAPITAL STRATEGY</h6>
                  <h2 className="display-4 fw-bold mb-4" style={{ color: 'var(--primary-color)', lineHeight: '1.1' }}>Creative <br className="d-none d-md-block"/> Capital</h2>
                  <div className="gold-separator mb-4"></div>
                  <p className="lead mb-4 fw-medium" style={{ color: 'var(--secondary-color)' }}>Unlocking value in asset-rich opportunities.</p>
                  <p className="mb-5 text-muted" style={{ lineHeight: '1.8' }}>
                    We provide flexible and imaginative capital to businesses with strong asset bases. Our team excels in identifying latent value and structuring deals that provide the liquidity and stability needed for long-term growth.
                  </p>
                  <Link href="/contact" className="btn btn-premium px-5 py-3">DISCUSS PARTNERSHIP</Link>
                </div>
              </div>
              
              <div className="col-lg-7 order-1 order-lg-2 fade-up">
                <div className="modern-composition">
                  <div className="main-image-frame">
                    <img src="https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=1200" className="main-image" alt="Creative Finance" />
                    <div className="image-overlay-vogue"></div>
                  </div>
                  <div className="experience-stamp">
                    <span className="stamp-num">100+</span>
                    <span className="stamp-text">COMPLEX<br/>DEALS</span>
                  </div>
                  <div className="decorative-grid d-none d-md-block"></div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* 6. 3 cards: Nimble Execution, Asset Expertise, Long-standing Relationships */}
        <section className="bg-light py-5">
          <div className="container">
            <div className="text-center mb-5 fade-up">
              <h2 className="section-title text-center">Core Strengths</h2>
            </div>
            <div className="row g-4">
              {valueCards.map((card, idx) => (
                <div key={idx} className="col-lg-4 col-md-6 fade-up">
                  <div className="luxury-card h-100 border-top border-gold border-3 p-4 p-md-5">
                    <div className="mb-4">
                      <i className={`bi ${card.icon} display-4 text-gold`}></i>
                    </div>
                    <h4 className="mb-3 fw-bold h5">{card.title}</h4>
                    <p className="text-muted small mb-0" style={{ lineHeight: '1.8' }}>{card.description}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* 7. A Specialized Team Section */}
        <section className="bg-white border-top py-5">
          <div className="container">
            <div className="row align-items-center g-5">
              <div className="col-lg-7 fade-up">
                <h2 className="section-title">A Specialized Team</h2>
                <p className="lead text-muted mb-5" style={{ lineHeight: '1.8' }}>
                  Our global investment team is comprised of specialists who have deep structuring experience including in the development and use of private securitization technology, as well as granular knowledge about the way hard and financial assets perform across economic cycles.
                </p>
                <Link href="/contact" className="btn btn-premium px-5 py-3">Meet Our Team</Link>
              </div>
              <div className="col-lg-5 fade-up d-none d-lg-block">
                <div className="p-2 border border-gold">
                  <img src="https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=800" className="img-fluid" alt="Specialized Team" />
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Footer />

      <style jsx>{`
        .gold-separator {
          width: 80px;
          height: 2px;
          background: var(--accent-gold);
        }

        .modern-composition {
          position: relative;
          height: 600px;
          display: flex;
          align-items: center;
          justify-content: flex-end;
        }
        .main-image-frame {
          width: 85%;
          height: 500px;
          overflow: hidden;
          position: relative;
          z-index: 2;
          box-shadow: 30px 30px 80px rgba(0,0,0,0.15);
        }
        .main-image {
          width: 100%;
          height: 100%;
          object-fit: cover;
          transition: transform 2s ease;
        }
        .modern-composition:hover .main-image {
          transform: scale(1.1);
        }
        .image-overlay-vogue {
          position: absolute;
          inset: 0;
          background: linear-gradient(45deg, rgba(31, 77, 58, 0.3), transparent);
        }
        .experience-stamp {
          position: absolute;
          bottom: 20px;
          right: -20px;
          background: var(--accent-gold);
          color: white;
          padding: 2rem;
          z-index: 4;
          text-align: center;
          min-width: 160px;
        }
        .stamp-num {
          display: block;
          font-size: 2.5rem;
          font-weight: 900;
          line-height: 1;
          margin-bottom: 5px;
          font-family: 'Montserrat', sans-serif;
        }
        .stamp-text {
          font-size: 0.65rem;
          font-weight: 800;
          letter-spacing: 2px;
          line-height: 1.3;
        }
        .decorative-grid {
          position: absolute;
          top: -30px;
          right: -30px;
          width: 200px;
          height: 200px;
          background-image: radial-gradient(#D4AF37 1px, transparent 1px);
          background-size: 20px 20px;
          opacity: 0.3;
          z-index: 1;
        }

        .py-section-minimalist {
          padding: 0;
          background: #1F4D3A;
          border-top: 1px solid rgba(212, 175, 55, 0.2);
          border-bottom: 1px solid rgba(212, 175, 55, 0.2);
        }
        .border-end-gold {
          border-right: 1px solid rgba(212, 175, 55, 0.15);
        }
        .minimal-value-wrap {
          display: flex;
          align-items: baseline;
          justify-content: center;
          gap: 4px;
          margin-bottom: 20px;
        }
        .min-number {
          font-family: 'Montserrat', sans-serif;
          font-size: 6rem;
          font-weight: 700;
          color: #ffffff;
          line-height: 0.8;
          margin: 0;
          letter-spacing: -2px;
        }
        .min-suffix {
          font-family: 'Montserrat', sans-serif;
          font-size: 2rem;
          color: var(--accent-gold);
          font-weight: 300;
        }
        .min-divider {
          width: 30px;
          height: 2px;
          background: var(--accent-gold);
          margin: 30px auto;
          transition: width 0.6s cubic-bezier(0.19, 1, 0.22, 1);
        }
        .minimal-fact-box:hover .min-divider {
          width: 60px;
        }
        .min-label {
          font-size: 0.9rem;
          font-weight: 700;
          letter-spacing: 3px;
          text-transform: uppercase;
          color: #ffffff;
          margin-bottom: 12px;
          font-family: 'Raleway', sans-serif;
        }
        .min-subtext {
          font-size: 0.8rem;
          color: rgba(255, 255, 255, 0.5);
          letter-spacing: 1px;
          margin: 0;
        }
        .arch-overlay {
          position: absolute;
          inset: 0;
          background-image: linear-gradient(rgba(255,255,255,0.03) 1px, transparent 1px),
                            linear-gradient(90deg, rgba(255,255,255,0.03) 1px, transparent 1px);
          background-size: 100px 100px;
          pointer-events: none;
        }

        @media (max-width: 991.98px) {
          .hero-section-standard {
            min-height: auto !important;
            padding-top: 120px !important;
            padding-bottom: 60px !important;
          }
          .display-3 {
            font-size: 2.5rem !important;
          }
          .border-end-gold {
            border-right: none;
            border-bottom: 1px solid rgba(212, 175, 55, 0.1);
          }
          .min-number {
            font-size: 4rem;
          }
          .modern-composition {
            height: auto;
            margin-top: 50px;
            justify-content: center;
          }
          .main-image-frame {
            width: 100%;
            height: 400px;
          }
          .experience-stamp {
            right: 0;
            padding: 1rem;
          }
        }
      `}</style>
    </>
  );
}
